name: Build and Store Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Build
      run: |
        python setup.py build --build-base build/

    - name: Debug Build Output
      run: |
        echo "Listing all files after build:"
        ls -R

    - name: Verify Build Directory
      run: |
        echo "Checking build directory..."
        ls -al build/ || echo "No build directory found!"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build/
